package main.java.com.projecteuler;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * <p>
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * <p>
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sumOfAll of the even-valued terms.
 */
public class EvenFibonacciNumbers {
    public static void main(String...args) {
        int previous = 0, current = 1, fibonacci = 0;
        int sum = 0, max = 4_0_00_000;
        while (fibonacci <= max) {
            fibonacci = previous + current;
            if (fibonacci % 2 == 0) {
                sum += fibonacci;
            }
            previous = current;
            current = fibonacci;
        }
        System.out.println("Sum of the even-valued terms : " + sum);
    }
}
